# System-wide .bashrc file for interactive bash(1) shells.

# To enable the settings / commands in this file for login shells as well,
# this file has to be sourced in /etc/profile.

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, overwrite the one in /etc/profile)
PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '

# Commented out, don't overwrite xterm -T "title" -n "icontitle" by default.
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
    ;;
*)
    ;;
esac

# enable bash completion in interactive shells
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# if the command-not-found package is installed, use it
if [ -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ]; then
	function command_not_found_handle {
	        # check because c-n-f could've been removed in the meantime
                if [ -x /usr/lib/command-not-found ]; then
		   /usr/lib/command-not-found -- "$1"
                   return $?
                elif [ -x /usr/share/command-not-found/command-not-found ]; then
		   /usr/share/command-not-found/command-not-found -- "$1"
                   return $?
		else
		   printf "%s: command not found\n" "$1" >&2
		   return 127
		fi
	}
fi

alias x11vnc-default="x11vnc -scale 4/7 -noxdamage -localhost -cursor X -noalphablend -cursorpos -display :0 -grabptr -notruecolor -bg"
alias vpn-htwk="sudo -- /usr/sbin/vpnc /etc/vpnc/htwk.conf"
alias vpn-pdev="sudo -- /usr/sbin/openvpn --dev tun0 --config /etc/openvpn/htwk-pdev.ovpn"
alias vpn-end="sudo -- /usr/bin/killall -u root vpnc"
alias s2r="sudo /usr/sbin/s2ram --force"
alias android_adb="sudo /usr/sbin/android_adb.sh"
alias grub-nextboot-win7="grub-set-default 6"
alias grub-nextboot-vmlinuz="grub-set-default 1,3"
export _JAVA_AWT_WM_NONREPARENTING=1

if [ "x$TERM" = "xlinux" ]; then
  setterm -blank 0
  tty | grep -qE 'tty1$'
  if [ $? -eq 0 ] && [ $(id -u) -ne 0 ]; then
    exec startx
  fi
fi
if [ "x$USER" = "xguest" ]; then
  exec startx
fi

export GEM_HOME=${HOME}/.gem
