#!/bin/sh

xrandr -s 0
xrdb -load $HOME/.Xdefaults
xsetroot -cursor_name left_ptr
xset b off
xset s off
xset -dpms

start-pulseaudio-x11

feh --bg-center ~/chai.jpg

# hide cursor when unused (DONT FORGET -noevents / BUG)
unclutter -idle 3 -root -noevents &

# Turn CapsLock into Control
xmodmap -e "clear lock" -e "keycode 66 = Control_R" -e "add Control = Control_R"

# starting gpg daemon
gpg-agent --daemon --use-standard-socket

# activating xscreensaver
acpi -b | grep -qE 'Discharging'
if [ $? -ne 0 ]; then
  xscreensaver -nosplash &
fi

# akonadi server (kde4.* compat)
if [ -x /usr/bin/akonadi_agent_server ]; then
  akonadi_agent_server &
fi

# activate trickled network bandwith control
trickled

if [ -x /usr/bin/xcompmgr ]; then
  /usr/bin/xcompmgr &
fi
if [ -x /usr/bin/ck-launch-session ]; then
  exec ck-launch-session dbus-launch ~/.cabal/bin/xmonad
else
  exec dbus-launch ~/.cabal/bin/xmonad
fi
