#!/bin/sh

# hide cursor when unused
unclutter -idle 3 -root &

# Turn CapsLock into Control
xmodmap -e "clear lock" -e "keycode 66 = Control_R" -e "add Control = Control_R"

# starting gpg daemon
gpg-agent --daemon --use-standard-socket

# activating xscreensaver
xscreensaver -nosplash &

# akonadi server (kde4.* compat)
if [ -x /usr/bin/akonadi_agent_server ]; then
  akonadi_agent_server &
fi

# activate trickled network bandwith control
trickled

exec ck-launch-session dbus-launch xmonad
